# Docker Compose for Chatting app
version: '3.7'
services:
  mongo:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  server:
    build: .
    image: chatting-app
    environment:
      DB_URL: "mongodb://mongo:27017/chatting-app"
      JWT_AUTH_SALT: amberyan
      REDIS_DOMAIN_NAME: redis      
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

# Storage Volumes (non-volatile)
volumes:
  mongodata:
    driver: local
